### PR TITLE
feat: add a right to create, download and delete backup

### PR DESCRIPTION
**Pull request by vincent-tarrit**
Hello, a quick PR to add some rights on the table actions

### CODE REVIEW

**Review by shuvroroy — APPROVED** [review]

**Comment by shuvroroy** [comment]
Thanks

**Comment by aliaswpeu** [comment]
After this I can't see the button to create and delete backup,
I'v got shield installed and I don't see where I can add those permissions, can i generate them somehow ?

**Comment by JackWH** [comment]
@aliaswpeu Same issue here. It can be fixed by adding the lines below to the `boot()` method in `AuthServiceProvider.php`. Adjust as needed to suit your permissions:

```php
Gate::define('create-backup', fn(User $user) => $user->isAdmin());
Gate::define('download-backup', fn(User $user) => $user->isDeveloper());
Gate::define('delete-backup', fn(User $user) => false);
```

It would've been helpful if this PR was backwards-compatible, documented, and could be controlled via the config file. The ability names (e.g. `create-backup`) don't follow normal convention (`createBackup`). This prevents them from being registered in `Policy` classes, at least without introducing a workaround.

**Comment by aliaswpeu** [comment]
> @aliaswpeu Same issue here. It can be fixed by adding the lines below to the `boot()` method in `AuthServiceProvider.php`. Adjust as needed to suit your permissions:
> 
> ```
> Gate::define('create-backup', fn(User $user) => $user->isAdmin());
> Gate::define('download-backup', fn(User $user) => $user->isDeveloper());
> Gate::define('delete-backup', fn(User $user) => false);
> ```
> 
> It would've been helpful if this PR was backwards-compatible, documented, and could be controlled via the config file. The ability names (e.g. `create-backup`) don't follow normal convention (`createBackup`). This prevents them from being registered in `Policy` classes, at least without introducing a workaround.

Thank You, I just downgraded this package in my project (it seems that it was the only thing added in the last update, so not an issue for me) and it's working fine without permission. Although it's a good feature to restrict access.

**Comment by mokhosh** [comment]
> @aliaswpeu Same issue here. It can be fixed by adding the lines below to the `boot()` method in `AuthServiceProvider.php`. Adjust as needed to suit your permissions:
> 
> ```
> Gate::define('create-backup', fn(User $user) => $user->isAdmin());
> Gate::define('download-backup', fn(User $user) => $user->isDeveloper());
> Gate::define('delete-backup', fn(User $user) => false);
> ```
> 
> It would've been helpful if this PR was backwards-compatible, documented, and could be controlled via the config file. The ability names (e.g. `create-backup`) don't follow normal convention (`createBackup`). This prevents them from being registered in `Policy` classes, at least without introducing a workaround.

This is worth being in the docs imo

**Pull request merged**
